{
  "checkpoints": [
    "{\n  \"trainable_name\": \"_objective\",\n  \"trial_id\": \"4522e_00002\",\n  \"config\": {\n    \"per_device_train_batch_size\": 12,\n    \"per_device_eval_batch_size\": 12,\n    \"num_train_epochs\": 10,\n    \"learning_rate\": 2.0921304830970556e-05,\n    \"weight_decay\": 0.016443457513284063\n  },\n  \"local_dir\": \"C:\\\\Users\\\\mandy\\\\ray_results\\\\lcpn\",\n  \"evaluated_params\": {\n    \"learning_rate\": 2.0921304830970556e-05,\n    \"weight_decay\": 0.016443457513284063\n  },\n  \"experiment_tag\": \"2\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 16,\n    \"gpu\": 1,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595ce000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944740300000000000008c0347505594473ff00000000000008c066d656d6f7279944700000000000000008c136f626a6563745f73746f72655f6d656d6f72799447000000000000000075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1649120647.436348,\n  \"logdir\": \"C:\\\\Users\\\\mandy\\\\ray_results\\\\lcpn\\\\_objective_4522e_00002_2_2022-04-05_03-04-02\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"C:\\\\Users\\\\mandy\\\\ray_results\\\\lcpn\\\\_objective_4522e_00002_2_2022-04-05_03-04-02\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 739, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 746, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 82, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1621, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=19972, ip=192.168.1.200, repr=<types.ImplicitFunc object at 0x000002D8E934EDC0>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 536, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 486, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 563, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 178, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 237, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 379, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 526, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=19972, ip=192.168.1.200, repr=<types.ImplicitFunc object at 0x000002D8E934EDC0>)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 705, in convert_to_tensors\\n    tensor = as_tensor(value)\\nValueError: too many dimensions 'str'\\n\\nDuring handling of the above exception, another exception occurred:\\n\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=19972, ip=192.168.1.200, repr=<types.ImplicitFunc object at 0x000002D8E934EDC0>)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 260, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 328, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 594, in _trainable_func\\n    output = fn()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\integrations.py\\\", line 282, in dynamic_modules_import_trainable\\n    return trainable(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\utils\\\\trainable.py\\\", line 344, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\integrations.py\\\", line 183, in _objective\\n    local_trainer.train(resume_from_checkpoint=checkpoint, trial=trial)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\trainer.py\\\", line 1290, in train\\n    for step, inputs in enumerate(epoch_iterator):\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\torch\\\\utils\\\\data\\\\dataloader.py\\\", line 521, in __next__\\n    data = self._next_data()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\torch\\\\utils\\\\data\\\\dataloader.py\\\", line 561, in _next_data\\n    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\torch\\\\utils\\\\data\\\\_utils\\\\fetch.py\\\", line 52, in fetch\\n    return self.collate_fn(data)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\data\\\\data_collator.py\\\", line 221, in __call__\\n    batch = self.tokenizer.pad(\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 2795, in pad\\n    return BatchEncoding(batch_outputs, tensor_type=return_tensors)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 210, in __init__\\n    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 721, in convert_to_tensors\\n    raise ValueError(\\nValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_to_cloud\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": 1,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005955f010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d944b018c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"_objective\",\n  \"trial_id\": \"4522e_00003\",\n  \"config\": {\n    \"per_device_train_batch_size\": 12,\n    \"per_device_eval_batch_size\": 12,\n    \"num_train_epochs\": 10,\n    \"learning_rate\": 1.4065852851773962e-05,\n    \"weight_decay\": 0.08675143843171859\n  },\n  \"local_dir\": \"C:\\\\Users\\\\mandy\\\\ray_results\\\\lcpn\",\n  \"evaluated_params\": {\n    \"learning_rate\": 1.4065852851773962e-05,\n    \"weight_decay\": 0.08675143843171859\n  },\n  \"experiment_tag\": \"3\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 16,\n    \"gpu\": 1,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595ce000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944740300000000000008c0347505594473ff00000000000008c066d656d6f7279944700000000000000008c136f626a6563745f73746f72655f6d656d6f72799447000000000000000075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1649120652.3766131,\n  \"logdir\": \"C:\\\\Users\\\\mandy\\\\ray_results\\\\lcpn\\\\_objective_4522e_00003_3_2022-04-05_03-04-07\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"C:\\\\Users\\\\mandy\\\\ray_results\\\\lcpn\\\\_objective_4522e_00003_3_2022-04-05_03-04-07\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 739, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 746, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 82, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1621, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=4460, ip=192.168.1.200, repr=<types.ImplicitFunc object at 0x0000015A9AA6FDC0>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 536, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 486, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 563, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 178, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 237, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 379, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 526, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=4460, ip=192.168.1.200, repr=<types.ImplicitFunc object at 0x0000015A9AA6FDC0>)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 705, in convert_to_tensors\\n    tensor = as_tensor(value)\\nValueError: too many dimensions 'str'\\n\\nDuring handling of the above exception, another exception occurred:\\n\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=4460, ip=192.168.1.200, repr=<types.ImplicitFunc object at 0x0000015A9AA6FDC0>)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 260, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 328, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 594, in _trainable_func\\n    output = fn()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\integrations.py\\\", line 282, in dynamic_modules_import_trainable\\n    return trainable(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\utils\\\\trainable.py\\\", line 344, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\integrations.py\\\", line 183, in _objective\\n    local_trainer.train(resume_from_checkpoint=checkpoint, trial=trial)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\trainer.py\\\", line 1290, in train\\n    for step, inputs in enumerate(epoch_iterator):\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\torch\\\\utils\\\\data\\\\dataloader.py\\\", line 521, in __next__\\n    data = self._next_data()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\torch\\\\utils\\\\data\\\\dataloader.py\\\", line 561, in _next_data\\n    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\torch\\\\utils\\\\data\\\\_utils\\\\fetch.py\\\", line 52, in fetch\\n    return self.collate_fn(data)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\data\\\\data_collator.py\\\", line 221, in __call__\\n    batch = self.tokenizer.pad(\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 2795, in pad\\n    return BatchEncoding(batch_outputs, tensor_type=return_tensors)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 210, in __init__\\n    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 721, in convert_to_tensors\\n    raise ValueError(\\nValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_to_cloud\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": 1,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005955f010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d944b018c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"_objective\",\n  \"trial_id\": \"4522e_00001\",\n  \"config\": {\n    \"per_device_train_batch_size\": 12,\n    \"per_device_eval_batch_size\": 12,\n    \"num_train_epochs\": 10,\n    \"learning_rate\": 6.123957592679836e-05,\n    \"weight_decay\": 0.06026718993550663\n  },\n  \"local_dir\": \"C:\\\\Users\\\\mandy\\\\ray_results\\\\lcpn\",\n  \"evaluated_params\": {\n    \"learning_rate\": 6.123957592679836e-05,\n    \"weight_decay\": 0.06026718993550663\n  },\n  \"experiment_tag\": \"1\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 16,\n    \"gpu\": 1,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595ce000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944740300000000000008c0347505594473ff00000000000008c066d656d6f7279944700000000000000008c136f626a6563745f73746f72655f6d656d6f72799447000000000000000075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1649120642.3666234,\n  \"logdir\": \"C:\\\\Users\\\\mandy\\\\ray_results\\\\lcpn\\\\_objective_4522e_00001_1_2022-04-05_03-03-57\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"C:\\\\Users\\\\mandy\\\\ray_results\\\\lcpn\\\\_objective_4522e_00001_1_2022-04-05_03-03-57\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 739, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 746, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 82, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1621, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=19716, ip=192.168.1.200, repr=<types.ImplicitFunc object at 0x000002078809ED60>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 536, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 486, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 563, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 178, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 237, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 379, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 526, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=19716, ip=192.168.1.200, repr=<types.ImplicitFunc object at 0x000002078809ED60>)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 705, in convert_to_tensors\\n    tensor = as_tensor(value)\\nValueError: too many dimensions 'str'\\n\\nDuring handling of the above exception, another exception occurred:\\n\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=19716, ip=192.168.1.200, repr=<types.ImplicitFunc object at 0x000002078809ED60>)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 260, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 328, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 594, in _trainable_func\\n    output = fn()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\integrations.py\\\", line 282, in dynamic_modules_import_trainable\\n    return trainable(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\utils\\\\trainable.py\\\", line 344, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\integrations.py\\\", line 183, in _objective\\n    local_trainer.train(resume_from_checkpoint=checkpoint, trial=trial)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\trainer.py\\\", line 1290, in train\\n    for step, inputs in enumerate(epoch_iterator):\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\torch\\\\utils\\\\data\\\\dataloader.py\\\", line 521, in __next__\\n    data = self._next_data()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\torch\\\\utils\\\\data\\\\dataloader.py\\\", line 561, in _next_data\\n    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\torch\\\\utils\\\\data\\\\_utils\\\\fetch.py\\\", line 52, in fetch\\n    return self.collate_fn(data)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\data\\\\data_collator.py\\\", line 221, in __call__\\n    batch = self.tokenizer.pad(\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 2795, in pad\\n    return BatchEncoding(batch_outputs, tensor_type=return_tensors)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 210, in __init__\\n    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 721, in convert_to_tensors\\n    raise ValueError(\\nValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_to_cloud\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": 1,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005955f010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d944b018c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"_objective\",\n  \"trial_id\": \"4522e_00000\",\n  \"config\": {\n    \"per_device_train_batch_size\": 12,\n    \"per_device_eval_batch_size\": 12,\n    \"num_train_epochs\": 10,\n    \"learning_rate\": 3.621780831931538e-05,\n    \"weight_decay\": 0.0951207163345817\n  },\n  \"local_dir\": \"C:\\\\Users\\\\mandy\\\\ray_results\\\\lcpn\",\n  \"evaluated_params\": {\n    \"learning_rate\": 3.621780831931538e-05,\n    \"weight_decay\": 0.0951207163345817\n  },\n  \"experiment_tag\": \"0\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 16,\n    \"gpu\": 1,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595ce000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944740300000000000008c0347505594473ff00000000000008c066d656d6f7279944700000000000000008c136f626a6563745f73746f72655f6d656d6f72799447000000000000000075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1649120637.3819115,\n  \"logdir\": \"C:\\\\Users\\\\mandy\\\\ray_results\\\\lcpn\\\\_objective_4522e_00000_0_2022-04-05_03-03-57\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"C:\\\\Users\\\\mandy\\\\ray_results\\\\lcpn\\\\_objective_4522e_00000_0_2022-04-05_03-03-57\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 739, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 746, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 82, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1621, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=13896, ip=192.168.1.200, repr=<types.ImplicitFunc object at 0x0000022BDF653E20>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 536, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 486, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 563, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 178, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 237, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 379, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 526, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=13896, ip=192.168.1.200, repr=<types.ImplicitFunc object at 0x0000022BDF653E20>)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 705, in convert_to_tensors\\n    tensor = as_tensor(value)\\nValueError: too many dimensions 'str'\\n\\nDuring handling of the above exception, another exception occurred:\\n\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=13896, ip=192.168.1.200, repr=<types.ImplicitFunc object at 0x0000022BDF653E20>)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 260, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 328, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 594, in _trainable_func\\n    output = fn()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\integrations.py\\\", line 282, in dynamic_modules_import_trainable\\n    return trainable(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\utils\\\\trainable.py\\\", line 344, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\integrations.py\\\", line 183, in _objective\\n    local_trainer.train(resume_from_checkpoint=checkpoint, trial=trial)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\trainer.py\\\", line 1290, in train\\n    for step, inputs in enumerate(epoch_iterator):\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\torch\\\\utils\\\\data\\\\dataloader.py\\\", line 521, in __next__\\n    data = self._next_data()\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\torch\\\\utils\\\\data\\\\dataloader.py\\\", line 561, in _next_data\\n    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\torch\\\\utils\\\\data\\\\_utils\\\\fetch.py\\\", line 52, in fetch\\n    return self.collate_fn(data)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\data\\\\data_collator.py\\\", line 221, in __call__\\n    batch = self.tokenizer.pad(\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 2795, in pad\\n    return BatchEncoding(batch_outputs, tensor_type=return_tensors)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 210, in __init__\\n    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)\\n  File \\\"C:\\\\Users\\\\mandy\\\\anaconda3\\\\envs\\\\gpu2\\\\lib\\\\site-packages\\\\transformers\\\\tokenization_utils_base.py\\\", line 721, in convert_to_tensors\\n    raise ValueError(\\nValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_to_cloud\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": 1,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005955f010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d944b018c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}"
  ],
  "runner_data": {
    "_max_pending_trials": 17,
    "_metric": null,
    "_total_time": 0,
    "_iteration": 108,
    "_has_errored": true,
    "_fail_fast": false,
    "_server_port": null,
    "_cached_trial_decisions": {},
    "_queued_trial_decisions": {},
    "_updated_queue": true,
    "_should_stop_experiment": false,
    "_local_checkpoint_dir": "C:\\Users\\mandy\\ray_results\\lcpn",
    "_remote_checkpoint_dir": null,
    "_stopper": {
      "_type": "CLOUDPICKLE_FALLBACK",
      "value": "80059527000000000000008c107261792e74756e652e73746f70706572948c0b4e6f6f7053746f707065729493942981942e"
    },
    "_resumed": false,
    "_start_time": 1649120637.2257445,
    "_last_checkpoint_time": -Infinity,
    "_session_str": "2022-04-05_03-03-57",
    "checkpoint_file": "C:\\Users\\mandy\\ray_results\\lcpn\\experiment_state-2022-04-05_03-03-57.json",
    "_checkpoint_period": "auto",
    "launch_web_server": false
  },
  "stats": {
    "start_time": 1649120637.2257445,
    "timestamp": 1649120657.4816651
  }
}